FROM python:3.9-slim

WORKDIR /hw4

RUN apt-get update

RUN pip install --upgrade pip

RUN pip install cassandra-driver

RUN pip install pandas

COPY ./cassandra/cassandra_client.py .

COPY ./write_to_cassandra.py .

COPY ./sample.tsv .

# COPY ./amazon_reviews_us_Books_v1_02.tsv .

ENTRYPOINT ["python3", "write_to_cassandra.py"]
