FROM python:3.9-slim

WORKDIR /hw8

RUN apt-get update

RUN pip install --upgrade pip

RUN pip install kafka-python

RUN pip install cassandra-driver

COPY read_from_kafka.py .

COPY cassandra/cassandra_client.py .

ENTRYPOINT ["python3", "read_from_kafka.py"]