version: '3.5'

services:
  zookeeper-server:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
      
  kafka-server:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    networks:
        - kafka-network

networks:
  kafka-network:
    external: false
    name: kafka-network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local